package plugin

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestInstall_CreatesFilesAndInjects(t *testing.T) {
	// Set up a fake project directory
	projectDir := t.TempDir()
	origDir, _ := os.Getwd()
	require.NoError(t, os.Chdir(projectDir))
	defer os.Chdir(origDir)

	// Create go.mod
	require.NoError(t, os.WriteFile(filepath.Join(projectDir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.22\n"), 0644))

	// Create config/routes.go
	require.NoError(t, os.MkdirAll(filepath.Join(projectDir, "config"), 0755))
	routesContent := `package config

import (
	"github.com/gin-gonic/gin"
)

func SetupRoutes(routes *gin.Engine) {

}
`
	require.NoError(t, os.WriteFile(filepath.Join(projectDir, "config/routes.go"), []byte(routesContent), 0644))

	// Create database/connection.go
	require.NoError(t, os.MkdirAll(filepath.Join(projectDir, "database"), 0755))
	dbContent := `package database

import "gorm.io/gorm"

var DB *gorm.DB

func RunMigrations() {
	DB.AutoMigrate()
}
`
	require.NoError(t, os.WriteFile(filepath.Join(projectDir, "database/connection.go"), []byte(dbContent), 0644))

	// Create .env
	require.NoError(t, os.WriteFile(filepath.Join(projectDir, ".env"), []byte("DB_HOST=localhost\n"), 0644))

	// Create a simple plugin
	pluginDir := t.TempDir()
	manifest := `
name: test-plugin
version: "1.0.0"
description: "Test plugin"
author: "tester"

directories:
  - "app/services"

files:
  - template: "service.go.tmpl"
    output: "app/services/test_service.go"

injections:
  - file: "config/routes.go"
    action: "insert_before_closing_brace"
    content: |2
      	routes.GET("/test", test.Handler)

env_vars:
  - name: "TEST_KEY"
    value: "test_value"
`
	require.NoError(t, os.WriteFile(filepath.Join(pluginDir, "plugin.yaml"), []byte(manifest), 0644))

	// Create template
	require.NoError(t, os.MkdirAll(filepath.Join(pluginDir, "templates"), 0755))
	tmplContent := `package services

// TestService generated by plugin {{.Name}}
func TestService() string {
	return "hello from {{.AppName}}"
}
`
	require.NoError(t, os.WriteFile(filepath.Join(pluginDir, "templates", "service.go.tmpl"), []byte(tmplContent), 0644))

	// Load and install
	m, err := LoadManifest(filepath.Join(pluginDir, "plugin.yaml"))
	require.NoError(t, err)
	require.NoError(t, Validate(m))

	err = Install(pluginDir, m, nil)
	require.NoError(t, err)

	// Verify file was created
	generated, err := os.ReadFile(filepath.Join(projectDir, "app/services/test_service.go"))
	require.NoError(t, err)
	assert.Contains(t, string(generated), "TestService")
	assert.Contains(t, string(generated), "hello from myapp")

	// Verify route injection
	routes, err := os.ReadFile(filepath.Join(projectDir, "config/routes.go"))
	require.NoError(t, err)
	assert.Contains(t, string(routes), "routes.GET(\"/test\", test.Handler)")

	// Verify env var injection
	envContent, err := os.ReadFile(filepath.Join(projectDir, ".env"))
	require.NoError(t, err)
	assert.Contains(t, string(envContent), "TEST_KEY=test_value")
}

func TestInstall_TemplateVariables(t *testing.T) {
	projectDir := t.TempDir()
	origDir, _ := os.Getwd()
	require.NoError(t, os.Chdir(projectDir))
	defer os.Chdir(origDir)

	require.NoError(t, os.WriteFile(filepath.Join(projectDir, "go.mod"), []byte("module github.com/test/myapp\n\ngo 1.22\n"), 0644))

	pluginDir := t.TempDir()
	manifest := `
name: var-test
version: "1.0.0"

variables:
  - name: greeting
    default: "hello"

files:
  - template: "greet.go.tmpl"
    output: "greet.go"
`
	require.NoError(t, os.WriteFile(filepath.Join(pluginDir, "plugin.yaml"), []byte(manifest), 0644))

	require.NoError(t, os.MkdirAll(filepath.Join(pluginDir, "templates"), 0755))
	require.NoError(t, os.WriteFile(filepath.Join(pluginDir, "templates", "greet.go.tmpl"),
		[]byte(`package main
// {{.Variables.greeting}} from {{.Name}}
`), 0644))

	m, err := LoadManifest(filepath.Join(pluginDir, "plugin.yaml"))
	require.NoError(t, err)

	// Test with override
	err = Install(pluginDir, m, map[string]string{"greeting": "hola"})
	require.NoError(t, err)

	content, err := os.ReadFile(filepath.Join(projectDir, "greet.go"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "hola from var-test")
}
